language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
after_success:
  - mocha test/**/*.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
