language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install -g bower
  - bower install
  - npm install -g istanbul
  - npm install -g coffee-script
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
