language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
  - npm install -g istanbul
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec test/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
