language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install -g bower less grunt-cli istanbul coffee-script
  - bower install
after_success:
  - cat ./coverage/lcov.info ./coverage/jasmine/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info ./coverage/jasmine/lcov.info | codeclimate
