language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - npm install -g bower less grunt-cli istanbul coffee-script
  - bower install
  - mkdir /tmp/storage
after_success:
  - cat ./coverage/lcov.info ./coverage/jasmine/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info ./coverage/jasmine/lcov.info | codeclimate
  - rm -rf ./coverage
